# Generated by Django 3.1.4 on 2021-07-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesAgentConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_url', models.CharField(help_text='Agent URL', max_length=200)),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
